# [Info]
# 左上角标题
site_name: 高羽的个人网站
site_url: https://blog.gaoyu.uk
site_author: 高羽
site_description: 高羽的个人网站

# Example of including CNAME in mkdocs.yml
extra_files:
  - CNAME

# [Navigtion]
nav:
  - 博客:
    - BLOG/index.md
    - 补全世界计划:
      - BLOG/BIG-PLAN/index.md
      - CS:
        - 面试: 
          - 海量数据面试套路: BLOG/BIG-PLAN/INTERVIEW/bigdata.md
        - 算法学习:
          - 始于学习开始之前: BLOG/BIG-PLAN/CS/ALGORITHM/learn-alg.md
          - 排序算法看这篇就够了: BLOG/BIG-PLAN/CS/ALGORITHM/SORT/learn-sort.md
          - 刷题之路:
            - 反转链表: BLOG/BIG-PLAN/CS/ALGORITHM/LINK/reserve-link.md
        - 基础:
          - 搞懂二进制: BLOG/BIG-PLAN/CS/learn-binary.md
        - 互联网圈:
          - 互联网黑话: REPRODUCE/internet-slang.md
      - 二次元: BLOG/BIG-PLAN/CS/index.md
      - 游戏: BLOG/BIG-PLAN/CS/index.md
    - 没有用的知识又增加了:
      - IOS录音M4A音频格式转MP3格式: BLOG/USELESS-KNOWLEDGE/MAC-NATIVE-APPS/IOS-M4A-2-MP3.md
  - 讲稿:
    - LECTURE/index.md
  - 开发:
    - DEVELOP/index.md
    - 知识积累: 
      - RESEARCH/index.md
      - 基础: 
        - RESEARCH/index.md
        - 操作系统: BLOG/BIG-PLAN/CS/OS/index.md
        - 网络: BLOG/BIG-PLAN/CS/NETWORK/index.md
      - 语言:
        - RESEARCH/index.md
        - Golang: BLOG/BIG-PLAN/LANGUAGE/GO/index.md
        - Java: 
          - BLOG/BIG-PLAN/LANGUAGE/JAVA/index.md
          - GC: BLOG/BIG-PLAN/LANGUAGE/JAVA/gc.md
          - JUC: BLOG/BIG-PLAN/LANGUAGE/JAVA/juc.md
          - Memory: BLOG/BIG-PLAN/LANGUAGE/JAVA/memory.md
        - Spirng:   
            - BLOG/BIG-PLAN/LANGUAGE/JAVA/spring/spring.md
            - Spring-Boot: BLOG/BIG-PLAN/LANGUAGE/JAVA/spring/spring-boot.md

      - 中间件:
        - RESEARCH/index.md
        - 存储: 
          - RESEARCH/index.md
          - CLICKHOUSE: BLOG/BIG-PLAN/MIDDLE-WARE/STORAGE/CLICKHOUSE/index.md
          - ELASTICSEARCH: BLOG/BIG-PLAN/MIDDLE-WARE/STORAGE/ELASTICSEARCH/index.md
          - MYSQL: BLOG/BIG-PLAN/MIDDLE-WARE/STORAGE/MYSQL/index.md
          - PG: BLOG/BIG-PLAN/MIDDLE-WARE/STORAGE/PG/index.md
        - MQ:
          - RESEARCH/index.md
          - KAFKA: BLOG/BIG-PLAN/MIDDLE-WARE/MQ/KAFKA/index.md
        - 分布式协调:
          - RESEARCH/index.md
          - ETCD: BLOG/BIG-PLAN/MIDDLE-WARE/DISTRIBUTED-COORDINATION/ETCD/index.md
          - ZOOKEEPER: BLOG/BIG-PLAN/MIDDLE-WARE/DISTRIBUTED-COORDINATION/ZOOKEEPER/index.md
        - 云原生:
          - RESEARCH/index.md
          - DOCKER: BLOG/BIG-PLAN/MIDDLE-WARE/CLOULD-NATIVE/DOCKER/index.md
          - K8S: BLOG/BIG-PLAN/MIDDLE-WARE/CLOULD-NATIVE/K8S/index.md
      - 工程:
        - 分布式:
          - RESEARCH/index.md
          - 分布式原理: BLOG/BIG-PLAN/DISTRIBUTED/distributed.md
        - 架构:
          - RESEARCH/index.md
          - 微服务架构: BLOG/BIG-PLAN/ARCHITECTURE/MICRO-SERVICE/index.md
        - 数据工程:
          - RESEARCH/index.md
          - 数据工程: BLOG/BIG-PLAN/DATA-ENGINEERING/index.md
        - 系统设计:
          - RESEARCH/index.md
          - 系统设计: BLOG/BIG-PLAN/SYSTEM-DESIGN/index.md
        - 高并发: 
          - RESEARCH/index.md
          - 高并发: BLOG/BIG-PLAN/SYSTEM-DESIGN/HIGH-CONCURRENCY/index.md
      - 后端面经:
        - 后端面经: BLOG/BIG-PLAN/INTERVIEW/rd.md
    - 项目积累:
      - 大模型文档平台
      - dayu平台
        - 日志检索
        - 威胁分析
      - 数字货币交易所
        - 撮合引擎
      - 差价合约交易平台
        - 行情推送系统
        - 跟单系统

  - 研究:
    - RESEARCH/index.md
  - 二次元:
    - 2/index.md
  - 随笔:
    - ESSAY/index.md
  - 转载:
    - REPRODUCE/index.md
  - 关于我:
    - ME/introduction.md
# [UI]
# [top]
theme:
  name: material
  custom_dir: overrides
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
  language: zh # 一些提示性的文字会变成中文
  #icon:
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    #repo: fontawesome/brands/github
  logo: images/SpongeBob3.jpg


# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css
